
version: "3"

services:
  public-node:
    container_name: public-node
    image: ltonetwork/public-node
    mem_reservation: 1g
    volumes:
      - ./volumes/public-node:/lto
    ports:
      - 6868:6868
      - 6869:6869
    environment:
      - LTO_NETWORK=TESTNET
      - LTO_WALLET_SEED=green obscure funny elite predict sibling income weasel dice dose zone october apart planet repair
      - LTO_WALLET_PASSWORD=Marine1775$$
      - LTO_DECLARED_ADDRESS=108.167.36.108:6868
      - LTO_ENABLE_REST_API=true
      - LTO_API_KEY=WagaFaso1120$$

    networks:
      - lto

networks:
  lto:
    driver: bridge
